export function getTranslatedCountryName(country) {
  const translatedCountry = translatedCountryName[country];
  return translatedCountry ? translatedCountry : country;
}

const translatedCountryName = {
  Afghanistan: "Afeganistão",
  "Aland Islands": "Ilhas de Aland",
  Albania: "Albânia",
  Algeria: "Argélia",
  "American Samoa": "Samoa Americana",
  Andorra: "Andorra",
  Angola: "Angola",
  Anguilla: "Anguilla",
  Antarctica: "Antártida",
  "Antigua and Barbuda": "Antígua e Barbuda",
  Argentina: "Argentina",
  Armenia: "Armênia",
  Aruba: "Aruba",
  Australia: "Austrália",
  Austria: "Áustria",
  Azerbaijan: "Azerbaijão",
  Bahamas: "Bahamas",
  Bahrain: "Bahrein",
  Bangladesh: "Bangladesh",
  Barbados: "Barbados",
  Belarus: "Bielorrússia",
  Belgium: "Bélgica",
  Belize: "Belize",
  Benin: "Benin",
  Bermuda: "Bermudas",
  Bhutan: "Butão",
  Bolivia: "Bolívia",
  "Bonaire, Saint Eustatius and Saba ": "Países Baixos Caribenhos",
  "Bosnia and Herzegovina": "Bósnia e Herzegovina",
  Botswana: "Botsuana",
  "Bouvet Island": "Ilha Bouvet",
  Brazil: "Brasil",
  "British Indian Ocean Territory": "Território do Oceano Índico Britânico",
  "British Virgin Islands": "Ilhas Virgens Britânicas",
  Brunei: "Brunei",
  Bulgaria: "Bulgária",
  "Burkina Faso": "Burkina Faso",
  Burundi: "Burundi",
  Cambodia: "Cambodja",
  Cameroon: "Camarões",
  Canada: "Canadá",
  "Cape Verde": "Cabo Verde",
  "Cayman Islands": "Ilhas Cayman",
  "Central African Republic": "República Centro-Africana",
  Chad: "Chade",
  Chile: "Chile",
  China: "China",
  "Christmas Island": "Ilha Christmas",
  "Cocos Islands": "Ilhas Cocos",
  Colombia: "Colômbia",
  Comoros: "Comores",
  "Cook Islands": "Ilhas Cook",
  "Costa Rica": "Costa Rica",
  Croatia: "Croácia",
  Cuba: "Cuba",
  Curacao: "Curaçao",
  Cyprus: "Chipre",
  "Czech Republic": "República Checa",
  Czechia: "Tchéquia",
  "Democratic Republic of the Congo": "República Democrática do Congo",
  Denmark: "Dinamarca",
  Djibouti: "Djibouti",
  Dominica: "Dominica",
  "Dominican Republic": "República Dominicana",
  "East Timor": "Timor-Leste",
  Ecuador: "Equador",
  Egypt: "Egito",
  "El Salvador": "El Salvador",
  "Equatorial Guinea": "Guiné Equatorial",
  Eritrea: "Eritreia",
  Estonia: "Estônia",
  Ethiopia: "Etiópia",
  "Falkland Islands": "Ilhas Malvinas",
  "Faroe Islands": "Ilhas Faroé",
  Fiji: "Fiji",
  Finland: "Finlândia",
  France: "França",
  "French Guiana": "Guiana Francesa",
  "French Polynesia": "Polinésia Francesa",
  "French Southern Territories": "Terras Austrais e Antárticas Francesas",
  Gabon: "Gabão",
  Gambia: "Gâmbia",
  Georgia: "Geórgia",
  Germany: "Alemanha",
  Ghana: "Gana",
  Gibraltar: "Gibraltar",
  Greece: "Grécia",
  Greenland: "Groenlândia",
  Grenada: "Granada",
  Guadeloupe: "Guadalupe",
  Guam: "Guam",
  Guatemala: "Guatemala",
  Guernsey: "Guernsey",
  "Guinea-Bissau": "Guiné-Bissau",
  Guinea: "Guiné",
  Guyana: "Guiana",
  Haiti: "Haiti",
  "Heard Island and McDonald Islands": "Ilha Heard e Ilhas McDonald",
  Honduras: "Honduras",
  "Hong Kong": "Hong Kong",
  Hungary: "Hungria",
  Iceland: "Islândia",
  India: "Índia",
  Indonesia: "Indonésia",
  Iran: "Irã",
  Iraq: "Iraque",
  Ireland: "Irlanda",
  "Isle of Man": "Ilha de Man",
  Israel: "Israel",
  Italy: "Itália",
  "Costa do Marfim": "CI",
  Jamaica: "Jamaica",
  Japan: "Japão",
  Jersey: "Jersey",
  Jordan: "Jordânia",
  Kazakhstan: "Cazaquistão",
  Kenya: "Quênia",
  Kiribati: "Quiribati",
  "Korea, South": "Coreia do Sul",
  Kosovo: "Kosovo",
  Kuwait: "Kuwait",
  Kyrgyzstan: "Quirguistão",
  Laos: "Laos",
  Latvia: "Letônia",
  Lebanon: "Líbano",
  Lesotho: "Lesoto",
  Liberia: "Libéria",
  Libya: "Líbia",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lituânia",
  Luxembourg: "Luxemburgo",
  Macao: "Macau",
  Macedonia: "Macedônia",
  Madagascar: "Madagascar",
  "Mainland China": "China continental",
  Malawi: "MMalawiW",
  Malaysia: "Malásia",
  Maldives: "Maldivas",
  Mali: "Mali",
  Malta: "Malta",
  "Marshall Islands": "Ilhas Marshall",
  Martinique: "Martinica",
  Mauritania: "Mauritânia",
  Mauritius: "Ilhas Maurício",
  Mayotte: "Mayotte",
  Mexico: "México",
  Micronesia: "Estados Federados da Micronésia",
  Moldova: "Moldávia",
  Monaco: "Mônaco",
  Mongolia: "Mongólia",
  Montenegro: "Montenegro",
  Montserrat: "Montserrat",
  Morocco: "Marrocos",
  Mozambique: "Moçambique",
  Myanmar: "Myanmar",
  Namibia: "Namíbia",
  Nauru: "Nauru",
  Nepal: "Nepal",
  Netherlands: "Países Baixos",
  "New Caledonia": "Nova Caledônia",
  "New Zealand": "Nova Zelândia",
  Nicaragua: "Nicarágua",
  Niger: "Níger",
  Nigeria: "Nigéria",
  Niue: "Niue",
  "Norfolk Island": "Ilha Norfolk",
  "North Korea": "Coreia do Norte",
  "Northern Mariana Islands": "Ilhas Marianas do Norte",
  Norway: "Noruega",
  Oman: "Omã",
  Pakistan: "Paquistão",
  Palau: "Palau",
  "Palestinian Territory": "Territórios Palestinos",
  Panama: "Panamá",
  "Papua New Guinea": "Papua-Nova Guiné",
  Paraguay: "Paraguai",
  Peru: "Peru",
  Philippines: "Filipinas",
  Pitcairn: "Ilhas Pitcairn",
  Poland: "Polônia",
  Portugal: "Portugal",
  "Puerto Rico": "Porto Rico",
  Qatar: "Catar",
  "Republic of the Congo": "Congo",
  Reunion: "Reunião",
  Romania: "Romênia",
  Russia: "Rússia",
  Rwanda: "Ruanda",
  "Saint Barthelemy": "São Bartolomeu",
  "Saint Helena": "Santa Helena",
  "Saint Kitts and Nevis": "São Cristóvão e Névis",
  "Saint Lucia": "Santa Lúcia",
  "Saint Martin": "Ilha de São Martinho",
  "Saint Pierre and Miquelon": "Saint-Pierre e Miquelon",
  "Saint Vincent and the Grenadines": "São Vicente e Granadinas",
  Samoa: "Samoa",
  "San Marino": "San Marino",
  "Sao Tome and Principe": "São Tomé e Príncipe",
  "Saudi Arabia": "Arábia Saudita",
  Senegal: "Senegal",
  Serbia: "Sérvia",
  Seychelles: "Seychelles",
  "Sierra Leone": "Serra Leoa",
  Singapore: "Singapura",
  "Sint Maarten": "Ilha de São Martinho",
  Slovakia: "Eslováquia",
  Slovenia: "Eslovênia",
  "Solomon Islands": "Ilhas Salomão",
  Somalia: "Somália",
  "South Africa": "África do Sul",
  "South Georgia and the South Sandwich Islands":
    "Ilhas Geórgia do Sul e Sandwich do Sul",
  "South Korea": "Coreia do Sul",
  "South Sudan": "Sudão do Sul",
  Spain: "Espanha",
  "Sri Lanka": "Sri Lanka",
  Sudan: "Sudão",
  Suriname: "Suriname",
  "Svalbard and Jan Mayen": "Svalbard e Jan Mayen",
  Swaziland: "Suazilândia",
  Sweden: "Suécia",
  Switzerland: "Suiça",
  Syria: "Síria",
  Taiwan: "Taiwan",
  "Taiwan*": "Taiwan*",
  Tajikistan: "Tajiquistão",
  Tanzania: "Tanzânia",
  Thailand: "Tailândia",
  Togo: "Togo",
  Tokelau: "Toquelau",
  Tonga: "Tonga",
  "Trinidad and Tobago": "Trindade e Tobago",
  Tunisia: "Tunísia",
  Turkey: "Turquia",
  Turkmenistan: "Turcomenistão",
  "Turks and Caicos Islands": "Ilhas Turcas e Caicos",
  Tuvalu: "Tuvalu",
  "U.S. Virgin Islands": "Ilhas Virgens Americanas",
  Uganda: "Uganda",
  Ukraine: "Ucrânia",
  "United Arab Emirates": "Emirados Árabes Unidos",
  "United Kingdom": "Reino Unido",
  "United States Minor Outlying Islands":
    "Ilhas Menores Distantes dos Estados Unidos",
  Uruguay: "Uruguai",
  US: "Estados Unidos",
  Uzbekistan: "Uzbequistão",
  Vanuatu: "Vanuatu",
  Vatican: "Vaticano",
  Venezuela: "Venezuela",
  Vietnam: "Vietnã",
  "Wallis and Futuna": "Wallis e Futuna",
  "Western Sahara": "Saara Ocidental",
  Yemen: "Iêmen",
  Zambia: "Zâmbia",
  Zimbabwe: "Zimbábue"
};
